### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by essorencz** [brainrotjs/brainrot.js#25]
![image](https://github.com/user-attachments/assets/d7cc8ec9-1da2-4777-96a2-50ea0b370a55)

Can't get it working, I tried everything :/

**Comment by essorencz** [comment]
I got it working somehow but now im getting this when I want to continue:

`2024-11-21 23:13:48 [2024-11-21 22:13:48 +0000] [1] [INFO] Starting gunicorn 23.0.0
2024-11-21 23:13:48 [2024-11-21 22:13:48 +0000] [1] [INFO] Listening at: http://127.0.0.1:8000 (1)
2024-11-21 23:13:48 [2024-11-21 22:13:48 +0000] [1] [INFO] Using worker: sync
2024-11-21 23:13:48 [2024-11-21 22:13:48 +0000] [7] [INFO] Booting worker with pid: 7
2024-11-21 23:13:48 [2024-11-21 22:13:48 +0000] [7] [ERROR] Exception in worker process
2024-11-21 23:13:48 Traceback (most recent call last):
2024-11-21 23:13:48   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
2024-11-21 23:13:48     worker.init_process()
2024-11-21 23:13:48   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
2024-11-21 23:13:48     self.load_wsgi()
2024-11-21 23:13:48   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
2024-11-21 23:13:48     self.wsgi = self.app.wsgi()
2024-11-21 23:13:48   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
2024-11-21 23:13:48     self.callable = self.load()
2024-11-21 23:13:48   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
2024-11-21 23:13:48     return self.load_wsgiapp()
2024-11-21 23:13:48   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
2024-11-21 23:13:48     return util.import_app(self.app_uri)
2024-11-21 23:13:48   File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
2024-11-21 23:13:48     mod = importlib.import_module(module)
2024-11-21 23:13:48   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2024-11-21 23:13:48     return _bootstrap._gcd_import(name[level:], package, level)
2024-11-21 23:13:48   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2024-11-21 23:13:48   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2024-11-21 23:13:48   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
2024-11-21 23:13:48 ModuleNotFoundError: No module named '\\'
2024-11-21 23:13:48 [2024-11-21 22:13:48 +0000] [7] [INFO] Worker exiting (pid: 7)
2024-11-21 23:13:48 [2024-11-21 22:13:48 +0000] [1] [ERROR] Worker (pid:7) exited with code 3
2024-11-21 23:13:48 [2024-11-21 22:13:48 +0000] [1] [ERROR] Shutting down: Master
2024-11-21 23:13:48 [2024-11-21 22:13:48 +0000] [1] [ERROR] Reason: Worker failed to boot.
2024-11-21 23:15:28 [2024-11-21 22:15:28 +0000] [1] [INFO] Starting gunicorn 23.0.0
2024-11-21 23:15:28 [2024-11-21 22:15:28 +0000] [1] [INFO] Listening at: http://127.0.0.1:8000 (1)
2024-11-21 23:15:28 [2024-11-21 22:15:28 +0000] [1] [INFO] Using worker: sync
2024-11-21 23:15:28 [2024-11-21 22:15:28 +0000] [7] [INFO] Booting worker with pid: 7
2024-11-21 23:15:28 [2024-11-21 22:15:28 +0000] [7] [ERROR] Exception in worker process
2024-11-21 23:15:28 Traceback (most recent call last):
2024-11-21 23:15:28   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
2024-11-21 23:15:28     worker.init_process()
2024-11-21 23:15:28   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
2024-11-21 23:15:28     self.load_wsgi()
2024-11-21 23:15:28   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
2024-11-21 23:15:28     self.wsgi = self.app.wsgi()
2024-11-21 23:15:28   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
2024-11-21 23:15:28     self.callable = self.load()
2024-11-21 23:15:28   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
2024-11-21 23:15:28     return self.load_wsgiapp()
2024-11-21 23:15:28   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
2024-11-21 23:15:28     return util.import_app(self.app_uri)
2024-11-21 23:15:28   File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
2024-11-21 23:15:28     mod = importlib.import_module(module)
2024-11-21 23:15:28   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2024-11-21 23:15:28     return _bootstrap._gcd_import(name[level:], package, level)
2024-11-21 23:15:28   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2024-11-21 23:15:28   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2024-11-21 23:15:28   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
2024-11-21 23:15:28 ModuleNotFoundError: No module named '\\'
2024-11-21 23:15:28 [2024-11-21 22:15:28 +0000] [7] [INFO] Worker exiting (pid: 7)
2024-11-21 23:15:28 [2024-11-21 22:15:28 +0000] [1] [ERROR] Worker (pid:7) exited with code 3
2024-11-21 23:15:28 [2024-11-21 22:15:28 +0000] [1] [ERROR] Shutting down: Master
2024-11-21 23:15:28 [2024-11-21 22:15:28 +0000] [1] [ERROR] Reason: Worker failed to boot.
2024-11-21 23:16:18 [2024-11-21 22:16:18 +0000] [1] [INFO] Starting gunicorn 23.0.0
2024-11-21 23:16:18 [2024-11-21 22:16:18 +0000] [1] [INFO] Listening at: http://127.0.0.1:8000 (1)
2024-11-21 23:16:18 [2024-11-21 22:16:18 +0000] [1] [INFO] Using worker: sync
2024-11-21 23:16:18 [2024-11-21 22:16:18 +0000] [7] [INFO] Booting worker with pid: 7
2024-11-21 23:16:18 [2024-11-21 22:16:18 +0000] [7] [ERROR] Exception in worker process
2024-11-21 23:16:18 Traceback (most recent call last):
2024-11-21 23:16:18   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
2024-11-21 23:16:18     worker.init_process()
2024-11-21 23:16:18   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
2024-11-21 23:16:18     self.load_wsgi()
2024-11-21 23:16:18   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
2024-11-21 23:16:18     self.wsgi = self.app.wsgi()
2024-11-21 23:16:18   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
2024-11-21 23:16:18     self.callable = self.load()
2024-11-21 23:16:18   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
2024-11-21 23:16:18     return self.load_wsgiapp()
2024-11-21 23:16:18   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
2024-11-21 23:16:18     return util.import_app(self.app_uri)
2024-11-21 23:16:18   File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
2024-11-21 23:16:18     mod = importlib.import_module(module)
2024-11-21 23:16:18   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2024-11-21 23:16:18     return _bootstrap._gcd_import(name[level:], package, level)
2024-11-21 23:16:18   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2024-11-21 23:16:18   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2024-11-21 23:16:18   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
2024-11-21 23:16:18 ModuleNotFoundError: No module named '\\'
2024-11-21 23:16:18 [2024-11-21 22:16:18 +0000] [7] [INFO] Worker exiting (pid: 7)
2024-11-21 23:16:18 [2024-11-21 22:16:18 +0000] [1] [ERROR] Worker (pid:7) exited with code 3
2024-11-21 23:16:18 [2024-11-21 22:16:18 +0000] [1] [ERROR] Shutting down: Master
2024-11-21 23:16:18 [2024-11-21 22:16:18 +0000] [1] [ERROR] Reason: Worker failed to boot.
`

**Comment by noahgsolomon** [comment]
what command did u run to get this errro
