### ISSUE TITLE
Error in Image Generation

### ISSUE THREAD

**Issue by GhostGamr** [brainrotjs/brainrot.js#32]
PS C:\Users\hrmra\Desktop\ytshortsgenerator\brainrot.js\generate> node localBuild.mjs
🔄 Initializing transcript.mjs module
🔄 Initializing eleven.mjs module
⭐ Starting generateTranscriptAudio with params: {
  local: true,
  topic: 'Jordan Peterson is being eaten by a bear and joe rogan is trying to kiss the bear',
  agentA: 'JORDAN_PETERSON',
  agentB: 'JOE_ROGAN',
  ai: true,
  duration: 1
}
📜 Getting transcript from transcriptFunction
🎬 Starting transcriptFunction with params: {
  topic: 'Jordan Peterson is being eaten by a bear and joe rogan is trying to kiss the bear',
  agentA: 'JORDAN_PETERSON',
  agentB: 'JOE_ROGAN',
  duration: 1
}
🔄 Attempt 1/5
📝 Generating transcript...
📝 Starting generateTranscript with params: {
  topic: 'Jordan Peterson is being eaten by a bear and joe rogan is trying to kiss the bear',
  agentA: 'JORDAN_PETERSON',
  agentB: 'JOE_ROGAN',
  duration: 1
}
🤖 Creating Groq chat completion...
✅ Chat completion received
📄 Content length: 1044
🔍 Parsing content...
✅ Valid transcript generated
📜 Transcript lines:
1. JORDAN_PETERSON: "Fascinating, Joe, this bear appears to be devouring me whole, and yet, you're attempting to kiss it. Can you explain the psychological underpinnings of this behavior? Is this some sort of primal attraction to the destructive force of nature?"
   🖼️ Asset: A close-up of a person's face being eaten by a bear, with another person leaning in to kiss the bear's cheek in the background
2. JOE_ROGAN: "Dude, I'm not just kissing the bear, I'm trying to tap into its primal energy. I mean, think about it, Jordan, you're being consumed by this beast, and I'm trying to connect with it on a deeper level. It's like, the ultimate form of intimacy, man. And also, I'm pretty sure the bear is into it, bro."
   🖼️ Asset: A person with a meditation-like expression, leaning in to kiss a massive grizzly bear's cheek, as the bear's jaws are wide open, devouring another person in tthe background
✅ Transcript generated: 2 entries
🖼️ Starting fetchValidImages
🔍 Starting fetchValidImages with params: { length: 2, ai: true, duration: 1 }
🤖 Using AI image generation
📸 Queueing image generation for transcript 0: A close-up of a person's face being eaten by a bear, with another person leaning in to kiss the bear's cheek in the background
🎨 Starting image generation for prompt: A close-up of a person's face being eaten by a bear, with another person leaning in to kiss the bear's cheek in the background    
1️⃣ Getting AI prompt
💭 Generating image prompt for: A close-up of a person's face being eaten by a bear, with another person leaning in to kiss the bear's cheek in the background
📸 Queueing image generation for transcript 1: A person with a meditation-like expression, leaning in to kiss a massive grizzly bear's cheek, as the bear's jaws are wide open, devouring another person in the background
🎨 Starting image generation for prompt: A person with a meditation-like expression, leaning in to kiss a massive grizzly bear's cheek, as the bear's jaws are wide open, devouring another person in the background
1️⃣ Getting AI prompt
💭 Generating image prompt for: A person with a meditation-like expression, leaning in to kiss a massive grizzly bear's cheek, as the bear's jaws are wide open, devouring another person in the background
⏳ Waiting for all image generations to complete
❌ Error generating prompt: NotFoundError: 404 The model `ft:gpt-3.5-turbo-1106:personal::8TEhcfKm` does not exist or you do not have access to it.
    at APIError.generate (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/node_modules/openai/error.mjs:50:20)
    at OpenAI.makeStatusError (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/node_modules/openai/core.mjs:286:25)
    at OpenAI.makeRequest (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/node_modules/openai/core.mjs:330:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async imagePrompt (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:282:20)
    at async imageGeneneration (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:298:18)
    at async Promise.all (index 0)
    at async fetchValidImages (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:201:20)
    at async generateTranscriptAudio (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:65:18)
    at async transcribeFunction (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/transcribe.mjs:106:33) {
  status: 404,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8f777defde7cc1b0-BLR',
    connection: 'keep-alive',
    'content-encoding': 'gzip',
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 25 Dec 2024 08:34:26 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=bbvYERITwVHlhf_9ql43q_WjQiw2lqY1TQsCxIbWH5A-1735115666-1.0.1.1-Y9GUO2HeosM04mZHZO6XfFfb3c66sA48C5ARJUlHdcw5InB5Ql268mEBqUW2y2aYKbR9ok.cDepwI.V0e4XNnw; path=/; expires=Wed, 25-Dec-24 09:04:26 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=8HgEv5_27j9eh74tMv_yUqwBg3Q9QFbUzlbZmBD.UyA-1735115666116-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Origin',
    'x-content-type-options': 'nosniff',
    'x-request-id': 'req_087cf415668233f64c5a8b2c1d742609'
  },
  request_id: 'req_087cf415668233f64c5a8b2c1d742609',
  error: {
    message: 'The model `ft:gpt-3.5-turbo-1106:personal::8TEhcfKm` does not exist or you do not have access to it.',
    type: 'invalid_request_error',
    param: null,
    code: 'model_not_found'
  },
  code: 'model_not_found',
  param: null,
  type: 'invalid_request_error'
}
❌ Error in imageGeneration: NotFoundError: 404 The model `ft:gpt-3.5-turbo-1106:personal::8TEhcfKm` does not exist or you do not have access to it.
    at APIError.generate (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/node_modules/openai/error.mjs:50:20)
    at OpenAI.makeStatusError (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/node_modules/openai/core.mjs:286:25)
    at OpenAI.makeRequest (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/node_modules/openai/core.mjs:330:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async imagePrompt (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:282:20)
    at async imageGeneneration (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:298:18)
    at async Promise.all (index 0)
    at async fetchValidImages (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:201:20)
    at async generateTranscriptAudio (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:65:18)
    at async transcribeFunction (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/transcribe.mjs:106:33) {
  status: 404,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8f777defde7cc1b0-BLR',
    connection: 'keep-alive',
    'content-encoding': 'gzip',
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 25 Dec 2024 08:34:26 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=bbvYERITwVHlhf_9ql43q_WjQiw2lqY1TQsCxIbWH5A-1735115666-1.0.1.1-Y9GUO2HeosM04mZHZO6XfFfb3c66sA48C5ARJUlHdcw5InB5Ql268mEBqUW2y2aYKbR9ok.cDepwI.V0e4XNnw; path=/; expires=Wed, 25-Dec-24 09:04:26 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=8HgEv5_27j9eh74tMv_yUqwBg3Q9QFbUzlbZmBD.UyA-1735115666116-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Origin',
    'x-content-type-options': 'nosniff',
    'x-request-id': 'req_087cf415668233f64c5a8b2c1d742609'
  },
  request_id: 'req_087cf415668233f64c5a8b2c1d742609',
  error: {
    message: 'The model `ft:gpt-3.5-turbo-1106:personal::8TEhcfKm` does not exist or you do not have access to it.',
    type: 'invalid_request_error',
    param: null,
    code: 'model_not_found'
  },
  code: 'model_not_found',
  param: null,
  type: 'invalid_request_error'
}
❌ Error generating prompt: NotFoundError: 404 The model `ft:gpt-3.5-turbo-1106:personal::8TEhcfKm` does not exist or you do not have access to it.
    at APIError.generate (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/node_modules/openai/error.mjs:50:20)
    at OpenAI.makeStatusError (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/node_modules/openai/core.mjs:286:25)
    at OpenAI.makeRequest (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/node_modules/openai/core.mjs:330:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async imagePrompt (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:282:20)
    at async imageGeneneration (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:298:18)
    at async Promise.all (index 1)
    at async fetchValidImages (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:201:20)
    at async generateTranscriptAudio (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:65:18)
    at async transcribeFunction (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/transcribe.mjs:106:33) {
  status: 404,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8f777defdb031d18-BLR',
    connection: 'keep-alive',
    'content-encoding': 'gzip',
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 25 Dec 2024 08:34:26 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=C.oxT1JOQz8NHGN_qETHzUg5zzSPw.yxziDeCRb35BU-1735115666-1.0.1.1-F05AVd3XWFSlTWffd4f73C0BAiAi7Duz4HoeKHZqfqW8O4CrR9uFukkcr72Pe5ykZZLxDo7ljXX2smvfPb4tyA; path=/; expires=Wed, 25-Dec-24 09:04:26 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=gY.nJHL4D6pbU1cp5MyIRyRPnY_lGXDqnPo_2mCG0qY-1735115666125-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Origin',
    'x-content-type-options': 'nosniff',
    'x-request-id': 'req_71214c36d0aef5a5abd4cb4edeb0545f'
  },
  request_id: 'req_71214c36d0aef5a5abd4cb4edeb0545f',
  error: {
    message: 'The model `ft:gpt-3.5-turbo-1106:personal::8TEhcfKm` does not exist or you do not have access to it.',
    type: 'invalid_request_error',
    param: null,
    code: 'model_not_found'
  },
  code: 'model_not_found',
  param: null,
  type: 'invalid_request_error'
}
❌ Error in imageGeneration: NotFoundError: 404 The model `ft:gpt-3.5-turbo-1106:personal::8TEhcfKm` does not exist or you do not have access to it.
    at APIError.generate (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/node_modules/openai/error.mjs:50:20)
    at OpenAI.makeStatusError (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/node_modules/openai/core.mjs:286:25)
    at OpenAI.makeRequest (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/node_modules/openai/core.mjs:330:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async imagePrompt (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:282:20)
    at async imageGeneneration (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:298:18)
    at async Promise.all (index 1)
    at async fetchValidImages (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:201:20)
    at async generateTranscriptAudio (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/eleven.mjs:65:18)
    at async transcribeFunction (file:///C:/Users/hrmra/Desktop/ytshortsgenerator/brainrot.js/generate/transcribe.mjs:106:33) {
  status: 404,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8f777defdb031d18-BLR',
    connection: 'keep-alive',
    'content-encoding': 'gzip',
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 25 Dec 2024 08:34:26 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=C.oxT1JOQz8NHGN_qETHzUg5zzSPw.yxziDeCRb35BU-1735115666-1.0.1.1-F05AVd3XWFSlTWffd4f73C0BAiAi7Duz4HoeKHZqfqW8O4CrR9uFukkcr72Pe5ykZZLxDo7ljXX2smvfPb4tyA; path=/; expires=Wed, 25-Dec-24 09:04:26 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=gY.nJHL4D6pbU1cp5MyIRyRPnY_lGXDqnPo_2mCG0qY-1735115666125-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Origin',
    'x-content-type-options': 'nosniff',
    'x-request-id': 'req_71214c36d0aef5a5abd4cb4edeb0545f'
  },
  request_id: 'req_71214c36d0aef5a5abd4cb4edeb0545f',
  error: {
    message: 'The model `ft:gpt-3.5-turbo-1106:personal::8TEhcfKm` does not exist or you do not have access to it.',
    type: 'invalid_request_error',
    param: null,
    code: 'model_not_found'
  },
  code: 'model_not_found',
  param: null,
  type: 'invalid_request_error'
}
✅ AI images generated: 2
✅ Images fetched: 2

**Comment by TheRodzz** [comment]
replace ```ft:gpt-3.5-turbo-1106:personal::8TEhcfKm``` with ```gpt-3.5-turbo```
